# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Bring It!' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!
 

 pod 'FacebookCore'
 pod 'FacebookLogin'
 pod 'SearchTextField'
 pod 'SwipeCellKit'
 pod 'Google/SignIn'
 pod 'Alamofire', '~> 4.5'
 
 pod 'SwiftyJSON'
 
  # Pods for Bring It!

  target 'Bring It!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bring It!UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
